### ISSUE TITLE
Version numbers 

### ISSUE THREAD

**Issue by HypoChloremic** [AroArz/StaG-SIS#1]
Exact dependencies are not provided amana. Does it work with all versions of `StaG`?

**Comment by AroArz** [comment]
Hey, sorry for the sparse documentation I've been intending to expand upon it. The `--develop` branch of StaG is the only branch that can run Snakemake with Singularity images. `master` and `dnbseq-prerpoc` uses conda, however, we noticed there was a problem with the conda compiled version of Kraken2 and so decided to transition into singularity. 

The dependencies you likely are missing if you're running StaG-SIS would be the databases as they are not included in the images. 

1. fork `https://github.com/AroArz/stag-mwc`
2. In your fork edit `config.yaml` in the develop branch to accurately reflect the databases on your server.
3. Assumming all your databases share the same mount point edit following lines `startscript.sh`
```
Database=/path/to/databases


-B $PWD,$Input:/input,$Output:/output_dir,$Workdir:/workdir,$Database:/path/to/databases
```
4. Then edit the following lines in `runscript.sh`
```
Database=/path/to/databases

git clone --branch develop YourForkedStaG .
```

Note: I've only tested StaG-SIS with the following config settings, you may run into unexpected errors if you choose to employ other steps.
```
#########################
# Pipeline steps included
#########################
qc_reads: True
host_removal: True
naive:
    assess_depth: False
    sketch_compare: False
taxonomic_profile:
    kaiju: False
    kraken2: True
    metaphlan2: False
functional_profile:
    humann2: False
antibiotic_resistance: False
mappers:
    bbmap: False
    bowtie2: False
assembly: False
binning: False
multiqc_report: True
```

Thus far the only side-effect we've noticed of singularity in singularity as root is permission changes to `/tmp`, `/proc`, `/sys`, and `/dev`.
